const actionTypes = {
  TEAM_SELECT: "SET/TEAM_SELECT",
  SELECT_TEAM: "SET/SELECT_TEAM",
  LOADING_PAGE: "SET/LOADING_PAGE",
  TEAMS_SELECT: "SET/TEAMS_SELECT",
  SET_JERSEY: "SET/SET_JERSEY",
  PLAYER_SELECT: "SET/PLAYER_SELECT",
  TEAM_SELECT: "SET/TEAM_SELECT"
};

export default actionTypes;
